### ISSUE TITLE
GRAPHITE_PREFIX doesn't substitute target_env when installing helm chart

### ISSUE THREAD

**Issue by david-smith-ft** [Financial-Times/content-collection-rw-neo4j#9]
You end up with a value of `coco.services.{{required "The target_env value is required for this app. Use helm upgrade ... --set target_env=... when installing." .Values.target_env}}.content-collection-rw-neo4j` 

I think if this was moved into the deployment itself (see example https://github.com/Financial-Times/api-policy-component/blob/master/helm/api-policy-component/templates/deployment.yaml#L55) then the variable would be substituted correctly.

**Comment by tamas-molnar** [comment]
Fixed in https://github.com/Financial-Times/content-collection-rw-neo4j/pull/10
